using System.Collections.Immutable;

namespace NpcManager.Cli.Tests;

internal static partial class Program
{
    private static readonly ImmutableHashSet<string> Preview231CommandNames =
        ImmutableHashSet.Create(
            StringComparer.Ordinal,
        "animation list",
        "animation tree",
        "appearance copy",
        "armor damage-resist",
        "armor propose",
        "armor write",
        "armor-addon propose",
        "armor-addon write",
        "assets index",
        "assets search",
        "body overlay bake",
        "body overlay patch",
        "body patch",
        "body reset",
        "body sidecar inspect",
        "body sidecar write",
        "body sliders inspect-preset",
        "body sliders resolve",
        "body transforms apply",
        "body weight normalize",
        "body weight redistribute",
        "body weight resolve",
        "bodygen build",
        "bodygen write",
        "capabilities",
        "changes list",
        "changes update",
        "diagnose",
        "face morph extended",
        "face morph patch",
        "face pose resolve",
        "face reset",
        "face sculpt patch",
        "face tint patch",
        "facegen analyze",
        "facegen bake-all",
        "facegen bake-all-native",
        "facegen build",
        "facegen build-geom",
        "facegen build-geom-bound",
        "facegen build-geom-nif",
        "facegen build-plugin",
        "facegen build-tint",
        "facegen build-tint-bound",
        "facegen build-tint-native",
        "facegen deploy",
        "facegen diagnose",
        "facegen hair-regions analyze",
        "facegen hair-regions apply",
        "facegen hair-regions preview",
        "facegen hair-regions propose",
        "facegen hair-regions verify",
        "facegen options",
        "facegen pack",
        "facegen plan-pack",
        "facegen resolve-providers",
        "facegen verify",
        "forms search",
        "gui",
        "headpart choices",
        "leveled-list propose",
        "leveled-list resolve",
        "leveled-list write",
        "load-order validate",
        "material-swap propose",
        "material-swap write",
        "npc assembly preflight",
        "npc create",
        "npc create-from-jslot",
        "npc create-from-preset",
        "npc create-from-reference",
        "npc dialogue analyze",
        "npc dialogue apply",
        "npc dialogue verify",
        "npc edit-package",
        "npc face-patch",
        "npc finish analyze",
        "npc finish apply",
        "npc finish verify",
        "npc follower-finish analyze",
        "npc follower-finish apply",
        "npc follower-finish pair-analyze",
        "npc follower-finish pair-apply",
        "npc follower-finish pair-verify",
        "npc follower-finish verify",
        "npc inspect",
        "npc list",
        "npc materialize-template",
        "npc patch",
        "npc placement interior analyze",
        "npc placement interior apply",
        "npc placement interior verify",
        "npc reset",
        "npc search",
        "npc voice discover",
        "npc voice import",
        "npc voice synthesize",
        "object-template propose",
        "object-template write",
        "outfit create",
        "outfit list",
        "outfit propose",
        "outfit write",
        "package archive",
        "package build",
        "package inspect",
        "package verify",
        "paint choices",
        "pipeline preset-to-npc",
        "plugin audit",
        "plugin deploy",
        "plugin verify",
        "plugin write",
        "plugins resolve-load-order",
        "plugins validate",
        "preset catalog",
        "preset create-from-reference",
        "preset design-propose",
        "preset diff",
        "preset export",
        "preset inspect",
        "preset resolve",
        "preview export-nif",
        "preview npc",
        "preview render",
        "preview reroll",
        "profile scan",
        "records list",
        "records propose",
        "render npc",
        "runtime smoke verify",
        "runtime smoke verify-all",
        "runtime-script build",
        "runtime-script deploy",
        "runtime-script inspect-vmad",
        "runtime-script package",
        "runtime-script propose",
        "runtime-script write",
        "schema export",
        "version",
        "workspace preflight",
        "workspace scan-generated"
        );
}
