using System.Collections.Immutable;
using NpcManager.Domain;

namespace NpcManager.Application;

public sealed record ReviewReceiptResult(
    bool Created,
    string Status,
    ReviewOutcome? Outcome,
    string? ReceiptPath,
    long? ReceiptSize,
    string? ReceiptSha256,
    string? WorkflowPath,
    long? WorkflowSize,
    string? WorkflowSha256,
    bool HumanVisualAuthority,
    bool RuntimeAuthority,
    bool PromotionAuthority);

public enum CommandExitCode
{
    Success = 0,
    GeneralFailure = 1,
    UsageError = 2,
    SecurityRefusal = 3,
    ValidationFailure = 4,
    Cancelled = 5
}

public sealed record CommandDescriptor(
    string Name,
    string Description,
    string SchemaVersion,
    bool Mutates,
    ImmutableArray<GameEdition> SupportedGames,
    ImmutableArray<string> Limitations);

public static class CommandCatalog
{
    public static ImmutableArray<CommandDescriptor> All { get; } =
    [
        Descriptor("capabilities", "Print the versioned command and capability manifest.", false),
        Descriptor("schema export", "Write the versioned schema and exit-code contract for one command or all commands.", true,
            "P12 bounded schema export; emits a K-local, no-overwrite JSON contract and does not execute a command."),
        Descriptor("version", "Print build and protocol versions.", false),
        Descriptor("diagnose", "Run a read-only local environment diagnosis.", false),
        Descriptor("workspace preflight", "Validate K-local roots or build a reviewed copied-Data intake before any NPC task.", false,
            "Read-only; --load-order binds the selected Skyrim plugin/master closure, sidecars, generated artifacts, and asset providers into a non-runtime intake fingerprint."),
        Descriptor("workspace scan-generated", "Scan a copied Data root for generated plugins and FaceGen sidecars.", false,
            "M2 read-only; scans the reference author marker and known FO4/SSE FaceGen paths without profile inference or mutation."),
        Descriptor("body sliders resolve", "Resolve BodySlide PIRT slider values from a typed preset.", false,
            "M5 bounded read-only resolution: parses PIRT position/UV sections, applies exact shape and case-insensitive morph matching, reports excluded or missing sliders, and never writes meshes or plugins."),
        Descriptor("body sliders inspect-preset", "Inspect a BodySlide SliderPreset XML without applying it.", false,
            "M7 bounded read-only import: parses SliderPresets/Preset name, set, groups, and ordered SetSlider rows in native percent values; no BodySlide execution, mesh generation, or runtime authority."),
        Descriptor("body sidecar inspect", "Validate and inspect a BodySlide .bssliders sidecar without applying it.", false,
            "M4 read-only; strict typed validation and canonical round-trip only; sidecar emission remains a later slice."),
        Descriptor("body sidecar write", "Write a deterministic NPC-specific BodySlide sidecar.", true,
            "M7 bounded writer; emits one typed NPC bodyMorphs entry with K-only, finite, no-overwrite, and reloadable JSON gates."),
        Descriptor("bodygen write", "Write deterministic Fallout 4 or Skyrim BodyGen configuration files.", true,
            "M7 bounded writer; consumes a typed assignment document and delegates to the existing dual-game BodyGen generator with strict K-only and no-overwrite gates."),
        Descriptor("body weight resolve", "Resolve Skyrim _0/_1 body-weight vertex interpolation from a typed manifest.", false,
            "M5 bounded read-only math: applies the ARMA 0x02 weight-slider gate, clamps weight/100, emits twin-minus-base sparse deltas, and does not parse NIF/ARMA files or claim runtime rendering."),
        Descriptor("body overlay patch", "Validate and order Fallout 4 or Skyrim SE body-overlay layers.", false,
            "M5 bounded read-only proposal: reproduces FO4 template/priority/UV/tint and SSE node/texture/tint/opacity routing with strict target validation; texture baking, plugin mutation, and runtime rendering remain separate."),
        Descriptor("body overlay bake", "Bake a deterministic Skyrim SE overlay layer stack to a K-local DDS artifact.", true,
            "M5 bounded CPU fold: optional facetint/detail, skee masks, and Face [OvlN] decals use explicit sRGB/linear and alpha rules; provider discovery, BCn compression, and runtime rendering remain separate."),
        Descriptor("body transforms apply", "Apply typed Skyrim RaceMenu node transforms and skin overrides to a new .jslot.", true,
            "M5 bounded metadata route: validates transform keys 30-33 and skin keys 7-9, preserves unrelated JSON, and refuses unsupported variants; NiOverride/co-save execution, providers, meshes, and runtime remain separate."),
        Descriptor("body reset", "Reset one body-editor section to an explicit construction snapshot.", true,
            "M5 bounded overlay reset: current and baseline .body.json snapshots are explicit, only the named body section is replaced, and plugins, .jslot files, meshes, and runtime state remain separate."),
        Descriptor("profile scan", "Read and fingerprint a copied game profile.", false,
            "M2 bounded read-only scan: requires an explicit K-local copied Data root, optionally binds a copied load-order manifest, hashes plugin bytes, and never infers or opens a live profile."),
        Descriptor("load-order validate", "Validate one explicit plugin against a copied load order.", false,
            "M2 compatibility-validation alias: requires an explicit --plugin and --load-order below the K-only lab root; it does not infer a live profile."),
        Descriptor("plugins resolve-load-order", "Resolve enabled plugin order from an explicit K-local manifest.", false,
            "M2 bounded load-order resolution; no live profile or load-order inference."),
        Descriptor("plugins validate", "Validate plugin masters, order, and game compatibility.", false,
            "M2 bounded compatibility checks; unsupported record families remain read-only."),
        Descriptor("assets index", "Index copied loose and archive assets, optionally writing a new artifact.", false, "M2 read-only; provider hashes and precedence are evidence, not mutation authority."),
        Descriptor("assets search", "Search normalized mesh or headpart choices with provider evidence.", false,
            "M2 bounded read-only choice enumeration; live preview, race predicates, and mutation remain planned."),
        Descriptor("headpart choices", "List Skyrim HDPT records compatible with one race, sex, and part type.", false,
            "Gate 3 read-only picker catalog over an explicit SHA-256-bound copied-plugin order; static race/sex/type compatibility and model routes are evidence, while preview pixels, caller mutation, runtime RaceCompatibility injection, and Skyrim rendering remain separate."),
        Descriptor("paint choices", "List RaceMenu paint registrations from winning compiled Skyrim scripts.", false,
            "Gate 3 read-only picker catalog over explicit K-local copied Data and plugin order; scans loaded-plugin BSA and loose Scripts PEX winners, returns provider hashes, and never infers from DDS filenames or claims texture/runtime authority."),
        Descriptor("forms search", "Search compatible FormID candidates by record signature and query.", false,
            "M2 bounded read-only candidate enumeration; desktop picker, draft rows, and field-specific predicates remain planned."),
        Descriptor("outfit list", "List typed OTFT outfit records and their item references.", false,
            "P09 bounded read-only enumeration; explicit copied Data roots and plugin order are required, with no live profile inference or preview rendering."),
        Descriptor("outfit propose", "Create a hash-bound typed OTFT create or override proposal.", true,
            "P09 bounded proposal only; validates source/master references and writes a new K-local JSON plan without mutating plugins or emitting unrelated records."),
        Descriptor("outfit write", "Materialize one hash-bound OTFT proposal into a new binary plugin.", true,
            "P09 bounded writer; revalidates the source hash and proposal, writes exactly one ordinary-plugin OTFT record for Fallout 4 or Skyrim SE, and independently reads the output back before promotion."),
        Descriptor("leveled-list propose", "Create a typed LVLI entry proposal.", true,
            "P09 bounded proposal only; validates entry levels/counts/chance, flags, masters, and ordering without binary plugin mutation."),
        Descriptor("leveled-list write", "Materialize one hash-bound LVLI proposal into a new binary plugin.", true,
            "P09 bounded writer; revalidates the source hash and proposal, writes exactly one ordinary-plugin LVLI record for Fallout 4 or Skyrim SE, and independently reads the output back before promotion. Skyrim SE maxCount and per-entry chance-none are intentionally limited to zero."),
        Descriptor("leveled-list resolve", "Resolve a typed LVLI proposal for deterministic preview.", true,
            "P09 bounded preview resolution; applies documented ChanceNone, UseAll, and CalculateEachInCount semantics to a K-local proposal with a supplied seed; level gates, binary records, and runtime remain separate."),
        Descriptor("armor propose", "Create a typed ARMO create or override proposal.", true,
            "P09 bounded proposal only; validates supported identity, model, slot, keyword, value, weight, health, rating, and addon references without binary plugin mutation."),
        Descriptor("armor write", "Materialize one hash-bound ARMO proposal into a new binary plugin.", true,
            "P09 bounded writer; revalidates the source hash and proposal, writes exactly one ordinary-plugin ARMO record for Fallout 4 or Skyrim SE, and independently reads the output back before promotion."),
        Descriptor("armor-addon write", "Materialize one hash-bound ARMA proposal into a new binary plugin.", true,
            "P09 bounded writer; revalidates the source hash and proposal, writes exactly one ordinary-plugin ARMA record for Fallout 4 or Skyrim SE, and independently reads the output back before promotion."),
        Descriptor("armor damage-resist", "Create a typed Fallout 4 ARMO damage-resistance proposal.", true,
            "P09 bounded ARMO proposal only; validates unique DMGT references and unsigned values without binary plugin mutation."),
        Descriptor("armor-addon propose", "Create a typed ARMA create or override proposal.", true,
            "P09 bounded proposal only; validates model, race, slot, skin, material, and sculpt routes with explicit game gates without binary plugin mutation."),
        Descriptor("material-swap propose", "Create a typed Fallout 4 MSWP create or override proposal.", true,
            "P09 bounded proposal only; validates ordered material substitutions and color-remap values without binary plugin mutation."),
        Descriptor("material-swap write", "Materialize one hash-bound MSWP proposal into a new binary plugin.", true,
            "P09 bounded Fallout 4 writer; revalidates the source hash and proposal, writes exactly one ordinary-plugin MSWP record, and independently reads the output back before promotion."),
        Descriptor("object-template propose", "Create a typed Fallout 4 OBTS combination/include proposal.", true,
            "P09 bounded proposal only; validates ordered object-template combinations, keywords, and OMOD includes without binary plugin mutation."),
        Descriptor("object-template write", "Materialize one Fallout 4 OBTS combination/include proposal.", true,
            "P09 bounded Fallout 4 writer; emits one ordinary ARMO record with OBTE/OBTF/FULL/OBTS/STOP, optionally binds typed OMOD property rows, remaps declared master-local references, and independently verifies the output."),
        Descriptor("changes list", "List stable field-level changes from an explicit session.", false,
            "P10 bounded read-only diff; explicit K-local session input is required and unchanged records are omitted."),
        Descriptor("changes update", "Propose an explicit reset or delete action for one record.", true,
            "P10 bounded action proposal; writes a review artifact and never mutates a plugin."),
        Descriptor("records propose", "Create a typed new, template-derived, or override record proposal.", true,
            "P10 bounded record proposal; explicit 24-bit FormID allocation is recorded and no plugin is mutated."),
        Descriptor("plugin write", "Write scalar NPC changes or one output-owned Skyrim HDPT to a fresh sandbox plugin.", true,
            "Consumes an NPC scalar proposal or Skyrim HDPT record proposal. HDPT append preserves existing records and master order; input composition requires its exact hash, private copies require fresh destinations, and output is independently reopened. Localized plugins and compressed HDPT clones are refused."),
        new CommandDescriptor(
            "npc create",
            "Create and independently verify one new Skyrim NPC with real FaceGeom, FaceTint, and package artifacts.",
            "1",
            true,
            ImmutableArray.Create(GameEdition.SkyrimSpecialEdition),
            ImmutableArray.Create(
                "Gate 1 qualified-carrier path: admitted female provider, static-validation role, ordinary ESP, and local FormID 0x000800 only; static proof is capped at STATIC_PASS_RUNTIME_REQUIRED.")),
        new CommandDescriptor(
            "npc create-from-preset",
            "Create a new Skyrim NPC or apply a complete RaceMenu preset to an existing source-owned NPC.",
            "1",
            true,
            ImmutableArray.Create(GameEdition.SkyrimSpecialEdition),
            ImmutableArray.Create(
                "Schema 1 creates a new NPC; schema 2 requires an exact copied source plugin/hash/local FormID and emits a true override with source-owner-keyed FaceGen and BodyGen. Static proof is capped at STATIC_PASS_RUNTIME_REQUIRED.")),
        new CommandDescriptor(
            "npc create-from-jslot",
            "Create and independently verify one new Skyrim NPC from reviewed RaceMenu JSlot authority.",
            "1",
            true,
            ImmutableArray.Create(GameEdition.SkyrimSpecialEdition),
            ImmutableArray.Create(
                "The typed request, JSlot, copied provider closure, and output root are hash-bound. Manager writes the plugin, FaceGeom, FaceTint, supported sidecars, manifest, and package tree; static completion remains runtime-required.")),
        new CommandDescriptor(
            "npc edit-package",
            "Edit an existing Skyrim NPC identity and independently verify one exact package.",
            "1",
            true,
            ImmutableArray.Create(GameEdition.SkyrimSpecialEdition),
            ImmutableArray.Create(
                "Gate 3 walking slice: EditorID and display name only. Appearance-affecting edits remain refused until their FaceGen rebuild transaction is implemented; static proof is capped at STATIC_PASS_RUNTIME_REQUIRED.")),
        Descriptor("npc list", "List NPC records from an explicit copied Data root with category and changed-only filters.", false, "M2 read-only; explicit Data root is required; full record-family fields remain planned."),
        Descriptor("npc search", "Search NPC EditorIDs and names in an explicit copied Data root.", false, "M2 read-only; explicit Data root is required; search is culture-invariant."),
        Descriptor("records list", "List typed records from an explicit copied plugin set.", false,
            "M2 bounded read-only enumeration: requires an explicit K-local Data root or plugin, supports signature/search filters, and never mutates or infers a live profile."),
        Descriptor("npc inspect", "Inspect one NPC as versioned structured data.", false, "M2 bounded inspection; unsupported record families are declared explicitly."),
        Descriptor("npc patch", "Create or apply a hash-bound NPC mutation proposal.", true, "M3 slice: identity, archetype, statistics, ordered keywords/attach-parent slots, factions, inventory, outfits, perks, actor effects, properties, and game-specific weight; explicit K-local output is required."),
        Descriptor("body patch", "Create or apply a hash-bound body skin or Fallout 4 body-region mutation proposal.", true, "M5 bounded routes: Fallout 4 NPC.WNAM set/clear and five-region NPC.MRSV values; --regions accepts named JSON or a K-local @file, while Skyrim WNAM/MRSV requests and unverified LooksMenu skin templates fail closed."),
        Descriptor("npc reset", "Reset one NPC section to an explicit loaded baseline.", true, "M3 bounded baseline reset: current and baseline are explicit same-plugin copies; only the named typed section may change, and unsupported null transitions fail closed."),
        Descriptor("npc face-patch", "Create or apply a typed PNAM/HCLF headpart and hair-color proposal.", true, "M4 bounded face section: explicit main headparts, race/sex/provider validation, and optional hair-color clear/set; preview, FaceGen, and runtime rendering remain separate."),
        Descriptor("npc materialize-template", "Materialize supported inherited NPC template categories into explicit fields.", true, "M3 bounded typed categories: stats, factions, spell list, and keywords; traits, AI, scripts, attacks, inventory, and other incomplete surfaces fail closed."),
        Descriptor("preset inspect", "Inspect a LooksMenu or RaceMenu preset.", false),
        new CommandDescriptor(
            "preset design-propose",
            "Create a deterministic landmark and description proposal from a hash-bound reference intake.",
            "1",
            true,
            ImmutableArray.Create(GameEdition.SkyrimSpecialEdition),
            ImmutableArray.Create(
                "P12-009 proposal only; it cannot fabricate reviewed resource choices, write a JSlot, build an NPC, or claim runtime likeness.")),
        new CommandDescriptor(
            "preset create-from-reference",
            "Create a deterministic authoring proposal or accepted RaceMenu JSlot from reviewed reference authority.",
            "1",
            true,
            ImmutableArray.Create(GameEdition.SkyrimSpecialEdition),
            ImmutableArray.Create(
                "P12-009 hash-bound proposal/apply transaction; static output remains STATIC_PASS_RUNTIME_REQUIRED.")),
        new CommandDescriptor(
            "npc create-from-reference",
            "Create a verified RaceMenu JSlot from reviewed reference authority and pass it to the existing NPC builder.",
            "1",
            true,
            ImmutableArray.Create(GameEdition.SkyrimSpecialEdition),
            ImmutableArray.Create(
                "P12-009 uses only the existing RaceMenu JSlot NPC transaction; static output never grants runtime or likeness authority.")),
        new CommandDescriptor(
            "npc follower-finish analyze",
            "Analyze one hash-bound simple Skyrim follower finish request and write a new proposal.",
            "1",
            true,
            ImmutableArray.Create(GameEdition.SkyrimSpecialEdition),
            ImmutableArray.Create(
                "One closed vanilla-framework follower, one simple exterior Sandbox, one placed actor/anchor, optional RGB correction, and ESL flagging; custom quests, dialogue, combat kits, outfits, navmesh, and runtime proof remain outside this command.")),
        new CommandDescriptor(
            "npc follower-finish apply",
            "Apply one reviewed simple Skyrim follower finish proposal to a new package and archive.",
            "1",
            true,
            ImmutableArray.Create(GameEdition.SkyrimSpecialEdition),
            ImmutableArray.Create(
                "One closed vanilla-framework follower, one simple exterior Sandbox, one placed actor/anchor, optional RGB correction, and ESL flagging; custom quests, dialogue, combat kits, outfits, navmesh, and runtime proof remain outside this command.")),
        new CommandDescriptor(
            "npc follower-finish verify",
            "Read and independently verify one completed simple Skyrim follower package.",
            "1",
            false,
            ImmutableArray.Create(GameEdition.SkyrimSpecialEdition),
            ImmutableArray.Create(
                "Read-only static verification of the bounded follower-finish package; runtime placement, appearance, recruitment, dismissal, and save behavior still require in-game proof.")),
        new CommandDescriptor(
            "npc finish analyze",
            "Analyze a hash-bound world-clean Finish Core request and write a new proposal.",
            "1",
            true,
            ImmutableArray.Create(GameEdition.SkyrimSpecialEdition),
            ImmutableArray.Create(
                "Finish Core authors follower, explicit optional AIDT, outfit, inventory, and a self-contained editor-location routine only; --validate-all is non-promoting and accumulates safely reachable phase diagnostics; no CELL, ACHR, placement, runtime, or visual authority is included.")),
        new CommandDescriptor(
            "npc finish apply",
            "Apply one reviewed Finish Core proposal to a new package and direct-install archive.",
            "1",
            true,
            ImmutableArray.Create(GameEdition.SkyrimSpecialEdition),
            ImmutableArray.Create(
                "The output preserves the source plugin identity and package-relative path plus appearance sidecars, emits no world/reference records, and remains STATIC_PASS_RUNTIME_REQUIRED; --validate-all uses disposable output and promotes nothing.")),
        new CommandDescriptor(
            "npc finish verify",
            "Reopen and independently verify one published world-clean Finish Core package.",
            "1",
            false,
            ImmutableArray.Create(GameEdition.SkyrimSpecialEdition),
            ImmutableArray.Create(
                "Read-only typed/raw/package/archive verification; placementIncluded, runtimeAuthority, and visualAuthority must remain false.")),
        new CommandDescriptor(
            "npc placement interior analyze",
            "Analyze an optional conflict-contained interior placement patch bound to one exact Finish Core package.",
            "1",
            true,
            ImmutableArray.Create(GameEdition.SkyrimSpecialEdition),
            ImmutableArray.Create(
                "Preview.227 static slice: verifies a complete copied load-order provider snapshot and derives one EDID-only interior CELL override plus one persistent ACHR; no core-package rewrite, pathing, runtime, or visual authority.")),
        new CommandDescriptor(
            "npc placement interior apply",
            "Apply one reviewed interior placement proposal as a separate optional light patch and archive.",
            "1",
            true,
            ImmutableArray.Create(GameEdition.SkyrimSpecialEdition),
            ImmutableArray.Create(
                "Preview.227 static slice: writes only a fresh sibling patch with one CELL and one ACHR, reports conflict-contained rather than conflict-free, and leaves runtime/release authority false.")),
        new CommandDescriptor(
            "npc placement interior verify",
            "Independently verify one generated interior placement patch and archive.",
            "1",
            false,
            ImmutableArray.Create(GameEdition.SkyrimSpecialEdition),
            ImmutableArray.Create(
                "Preview.227 read-only raw topology and archive verification; Skyrim placement, pathing, discovery, recruitment, save/reload, and visual behavior still require the runtime checkpoint.")),
        new CommandDescriptor(
            "npc follower-finish pair-analyze",
            "Analyze one hash-bound schema-3 paired Skyrim follower finish request.",
            "3",
            true,
            ImmutableArray.Create(GameEdition.SkyrimSpecialEdition),
            ImmutableArray.Create(
                "Current schema 3 reviews bounded companion FaceGeom HairTint and private outfit/inventory finish plus the accepted subject/provider route, preserves companion fields outside that reviewed slice, and writes only a proposal; legacy schema 2 remains accepted for compatibility.")),
        new CommandDescriptor(
            "npc follower-finish pair-apply",
            "Apply one reviewed schema-3 paired follower finish proposal.",
            "3",
            true,
            ImmutableArray.Create(GameEdition.SkyrimSpecialEdition),
            ImmutableArray.Create(
                "Applies only the reviewed subject records and bounded companion FaceGeom HairTint/private outfit-inventory fields, preserves companion fields outside that reviewed slice, and writes one deterministic two-plugin package; legacy schema 2 remains accepted for compatibility and runtime authority remains false.")),
        new CommandDescriptor(
            "npc follower-finish pair-verify",
            "Reopen and verify one schema-3 paired follower package.",
            "3",
            false,
            ImmutableArray.Create(GameEdition.SkyrimSpecialEdition),
            ImmutableArray.Create(
                "Read-only static verification covers both actor payloads, bounded companion FaceGeom HairTint/private outfit-inventory fields, subject plugin semantics, package inventory, and archive hashes; legacy schema 2 remains accepted for compatibility and runtime authority remains false.")),
        new CommandDescriptor(
            "preset catalog",
            "Catalog admitted RaceMenu .jslot presets in one copied K-local folder.",
            "1",
            false,
            ImmutableArray.Create(GameEdition.SkyrimSpecialEdition),
            ImmutableArray.Create(
                "Read-only flat catalog with immutable source hashes. Optional --data-root/--plugins/--race/--sex enables copied-provider HDPT/RACE compatibility; --compatible-only fails closed when runtime RaceCompatibility insertions are unmodeled. Runtime authority is never implied.")),
        Descriptor("preset export", "Write a deterministic LooksMenu or RaceMenu preset copy.", true),
        Descriptor("preset diff", "Compare two typed preset models.", false),
        Descriptor("preset resolve", "Resolve a portable Plugin|FormID identifier against an explicit load-order map.", false),
        Descriptor("appearance copy", "Copy selected typed appearance sections from one preset into another.", true,
            "M4 bounded Copy/Paste Look: explicit K-local source/target presets, selected categories, and a new non-overwriting output; NPC record-only categories fail visibly."),
        Descriptor("facegen analyze", "Analyze FaceGen applicability without writing (alias for facegen diagnose).", false,
            "M5 compatibility alias; uses the typed FaceGen diagnosis contract and preserves its explicit K-local manifest and non-runtime limits."),
        Descriptor("facegen diagnose", "Diagnose typed FaceGen shape applicability without writing.", false),
        Descriptor("facegen verify", "Verify FaceGen shape safety and reject zero or poisoned output.", false),
        SkyrimDescriptor("facegen hair-regions analyze", "Analyze exact FaceGeom HairTint regions and write a Preserve-default assignment template.", true,
            "Hash-bound K-local analysis only; writes canonical JSON, never modifies the source NIF, and grants no visual or runtime authority."),
        SkyrimDescriptor("facegen hair-regions propose", "Create an exact byte-bound dual-tone FaceGeom HairTint proposal.", true,
            "Writes one canonical proposal from exact analysis/request bytes; no NIF is changed."),
        SkyrimDescriptor("facegen hair-regions preview", "Render a reviewed off-engine preview of one exact HairTint proposal.", true,
            "Production composes exact candidate/provider evidence through the packaged pinned Blender/PyNifly renderer and atomically publishes one complete verified private bundle; off-engine visual and Skyrim runtime authority remain false."),
        SkyrimDescriptor("facegen hair-regions apply", "Apply one exact dual-tone HairTint proposal to a new FaceGeom NIF.", true,
            "Writes only authorized fixed-width HairTint envelopes plus a canonical manifest, with no overwrite."),
        SkyrimDescriptor("facegen hair-regions verify", "Independently verify one applied HairTint transaction.", false,
            "Read-only independent verification; visual and runtime authority remain false."),
        Descriptor("facegen build-geom", "Write a deterministic semantic FaceGeom build artifact.", true,
            "M5 bounded build plan: validates manifest shape safety and records selected shapes, headparts, morphs, and texture routes; it does not emit a game-loadable NIF until a vetted codec is admitted."),
        Descriptor("facegen build-geom-nif", "Bake selected TRI morphs into a sandbox FaceGeom NIF.", true,
            "M9 bounded binary sandbox: imports one copied head NIF plus adjacent TRI files through pinned Blender/PyNifly, bakes explicit morph values, and independently binds hashes; provider resolution, game-loadability, deployment, and runtime appearance remain separate."),
        Descriptor("facegen build-geom-bound", "Build a FaceGeom NIF at the canonical provider path for an explicit NPC load order.", true,
            "M9 bounded provider-bound build: resolves the pinned canonical FaceGeom NIF, requires one copied loose provider plus adjacent TRI evidence, and writes a distinct K-local output tree through the hash-pinned exporter; plugin loadability, deployment, and runtime rendering remain separate."),
        Descriptor("facegen build-tint", "Write a deterministic FaceTint build artifact and optional BGRA8 DDS.", true,
            "M5 bounded build: validates square resolution, format metadata, alpha/channel conventions, and ordered resolved tint layers; --dds-output emits an auditable DDS through the hash-pinned BGRA8/BC3/BC7 encoder boundary, while live provider resolution and game-facing texture binding remain separate."),
        Descriptor("facegen build-tint-bound", "Build a FaceTint DDS at the canonical provider path for an explicit NPC load order.", true,
            "M9 bounded provider-bound build: resolves the pinned FO4/SSE canonical FaceGen path, requires one copied loose provider and a manifest reference to that path, then writes a distinct K-local output tree; plugin loadability, deployment, and runtime rendering remain separate."),
        Descriptor("facegen build-tint-native", "Compose a native Skyrim FaceTint DDS from winning NPC, RACE, CLFM, and mask records.", true,
            "SKY-GUI-025 bounded native build: requires an explicit K-local copied Data root and ascending plugin order, binds record and loose/BSA mask hashes, emits a new 512x512 DXT5 DDS, and never claims runtime authority."),
        Descriptor("facegen options", "Validate or write a typed, game-aware CharGen/FaceGen options artifact.", true,
            "M4 bounded configuration: deterministic JSON and unsupported-combination diagnostics; it does not bake textures or claim runtime appearance."),
        Descriptor("face tint patch", "Create or apply an ordered Fallout 4 or Skyrim SE NPC face-tint patch.", true,
            "M4 bounded writer: FO4 TETI/TEND 1/5/7-byte layouts or Skyrim TINI/TINC/TINV/TIAS authored layers; race/provider resolution, RaceMenu mask sidecars, and runtime preview remain separate."),
        Descriptor("face morph patch", "Create or apply Skyrim native NAM9/NAMA face morphs.", true,
            "M4 bounded Skyrim writer: 18 NAM9 sliders, preserved trailing value, and four NAMA family values; RaceMenu extended morphs, sculpt, and runtime remain separate."),
        Descriptor("face morph extended", "Create or apply Skyrim RaceMenu extended name/value morphs.", true,
            "M4 bounded .jslot customMorphs patch: preserves unrelated JSON, reports uncatalogued names, and never claims mesh deformation or runtime rendering."),
        Descriptor("face sculpt patch", "Create or apply Skyrim RaceMenu per-shape sculpt blocks.", true,
            "M5 bounded .jslot morphs.sculpt patch: validates host identity, vertex counts, finite divisor-scaled deltas, and preservation; TRI topology, FaceGeom generation, and runtime rendering remain separate."),
        Descriptor("face pose resolve", "Resolve a deterministic face-bone and vertex-morph pose artifact.", false,
            "M5 bounded pose math: additive FMRS region deltas and declaration-ordered vertex channels; TRI topology, skinning, rendering, and runtime remain separate."),
        Descriptor("face reset", "Reset one face-editor section to an explicit construction snapshot.", true,
            "M5 bounded overlay reset: current and baseline .face.json snapshots are explicit, only the named tab payload is replaced, and FaceGen or runtime rendering remain separate."),
        Descriptor("body weight normalize", "Normalize Fallout 4 thin/muscular/fat barycentric weights.", false,
            "M5 bounded WeightTriangleControl math: non-negative clamping, unit-simplex normalization, and the pinned degenerate fallback."),
        Descriptor("body weight redistribute", "Move one Fallout 4 body-weight axis while preserving the other-axis ratio.", false,
            "M5 bounded slider math: clamp the selected axis and proportionally redistribute the remainder; no plugin write is performed by this helper."),
        Descriptor("facegen build", "Apply named game-aware FaceGen corrections in a sandbox.", true,
            "M5 bounded correction plan: strict FaceGen shape safety plus explicit ghoul/brow/mouth Fallout 4 and overlay/detail Skyrim SE decisions; NIF mutation, provider resolution, and runtime remain separate."),
        Descriptor("facegen bake-all", "Analyze an explicit batch of NPC FaceGen manifests.", true,
            "M5 bounded batch report: every manifest is classified passed/skipped/failed and any failed item forces a validation exit; NIF/DDS generation, plugin enumeration, and runtime remain separate."),
        Descriptor("facegen bake-all-native", "Bake canonical Skyrim FaceGeom NIF and FaceTint DDS pairs from a copied Data load order.", true,
            "SKY-GUI-025 real static batch: discovers winning NPC records from an explicit K-local copied Data root, bakes sequential atomic NIF/DDS pairs, retains verified earlier successes, and never claims runtime authority."),
        Descriptor("facegen build-plugin", "Build a semantic FaceGen report for one winning plugin target.", true,
            "M5 bounded plugin-target report: only entries whose winningPlugin matches --plugin receive derived FaceGen/<plugin>/<FormID>.json paths; cross-plugin leakage, NIF/DDS generation, and runtime remain separate."),
        Descriptor("facegen resolve-providers", "Resolve canonical FaceGen paths and copied-Data provider evidence for one NPC.", false,
            "M9 read-only provider-path slice: derives the pinned upstream FO4/SSE FaceGen filenames from an explicit load order and ESL-aware local FormID, reports copied loose/archive hashes, and does not claim game loadability or runtime appearance."),
        Descriptor("facegen plan-pack", "Plan one FaceGen loose-file bundle for the upstream packer contract.", false,
            "M9 read-only pack-plan slice: maps canonical entries to debug-sandbox sources, required/optional inputs, shared-neutral-detail deduplication, and main/textures archive roles without writing or deleting archives."),
        Descriptor("facegen pack", "Materialize a hash-bound K-local FaceGen package.", true,
            "M5 bounded package slice: copies the explicit anchor plugin and present canonical FO4/SSE FaceGen providers into a new Data package with source/output hashes and atomic no-overwrite gates; live deployment, archive serialization, and runtime appearance remain separate."),
        Descriptor("facegen deploy", "Deploy a hash-bound FaceGen package to a copied Data root.", true,
            "M9 bounded deployment: consumes a validated FaceGen pack manifest, preflights every canonical plugin/FaceGeom/FaceTint/provider file, promotes only into an explicit K-local copied Data root, treats identical files as idempotent, refuses conflicts and reparse paths, and never claims game loadability or runtime appearance."),
        Descriptor("preview render", "Write deterministic composite NPC scene evidence.", true,
            "M6 bounded scene-input report with optional K-local Blender/PyNifly PNG rendering: validates face/body/hair/outfit/accessory assets, provider labels, hashes, optional --visible/--morphs category toggles, explicit --outfit/--variant selection, versioned --camera/--lighting presets, and manifest-bound --animation frame/time metadata; it does not export NIFs or claim runtime appearance."),
        Descriptor("preview npc", "Compose and render one selected Skyrim NPC from reviewed providers.", true,
            "High-fidelity off-engine inspection only: resolves the selected NPC's exact copied/plugin/package providers into six textured views, refuses unsupported UBE runtime composition, never mutates source inputs, and never grants runtime or likeness authority."),
        Descriptor("preview reroll", "Choose a reproducible preview variant.", true,
            "M6 bounded SplitMix64 choice report: binds --npc and --seed to a validated manifest variant catalog and records the selected candidate; it does not randomize live records, render pixels, or claim runtime appearance."),
        Descriptor("preview export-nif", "Write a sandbox-only preview NIF export plan or binary artifact.", true,
            "M6 bounded export-plan report plus optional K-local hash-bound Blender/PyNifly mesh-only NIF export; independent block-table verification is included, while game-specific provider semantics, deployment, and runtime remain gated."),
        Descriptor("animation list", "List manifest-bound animation clips using the pinned picker taxonomy.", false,
            "M6 bounded read-only discovery: mirrors role/category/folder, gender, first-person, additive, and behavior-graph provenance metadata with deterministic filtering; it does not execute HKX behavior graphs or claim runtime reachability."),
        Descriptor("animation tree", "Project animation clips into the pinned picker hierarchy.", false,
            "M6 bounded read-only discovery: groups filtered clips by role/folder and IDLE gesture category with deterministic leaf labels; it reuses animation-list validation and does not execute HKX behavior graphs or claim runtime reachability."),
        Descriptor("bodygen build", "Build body morph sidecars in a sandbox.", true,
            "M7 bounded writer; emits deterministic dual-game BodyGen sidecars under an explicit K-local output root and never infers a live profile."),
        Descriptor("runtime-script propose", "Create a typed, hash-bound NPC apply-script VMAD proposal.", true,
            "P11 bounded proposal: validates the pinned FO4/SSE script property API, object-reference syntax, parallel arrays, and fragment ranges; source-bound binary materialization is exposed by runtime-script write, while PEX installation and runtime execution remain separate."),
        Descriptor("runtime-script build", "Inspect and record the pinned Papyrus source/PEX pair.", true,
            "P11 bounded evidence: runs the pinned Caprica PEX inspector, compares PSC and PEX APIs, records compiler-manifest/dependency/hash evidence, and never installs scripts or claims runtime behavior."),
        Descriptor("runtime-script write", "Materialize a source-bound apply-script VMAD proposal into a copied NPC plugin.", true,
            "P11 bounded binary slice: preserves non-owned NPC VMAD scripts, replaces the reserved apply-script prefix, writes the pinned FO4/SSE property set, and verifies round-trip semantics; PEX installation and runtime execution remain separate."),
        Descriptor("runtime-script package", "Package the game-specific compiled apply script beside VMAD output.", true,
            "P11 bounded package slice: copies only the pinned NPCM_Manolov_ApplyFO4 or NPCM_Manolov_ApplySSE PEX into a new K-local Data/Scripts tree with source and output hashes; PEX inspection, deployment, and runtime execution remain separate."),
        Descriptor("runtime-script deploy", "Install a packaged apply script into a copied Data root.", true,
            "M9 bounded deployment slice: installs only the source-bound game-specific apply PEX under a K-local copied Data/Scripts root, treats an identical file as idempotent, refuses conflicts and reparse paths, and never targets the protected live root or claims runtime execution."),
        Descriptor("runtime-script inspect-vmad", "Inspect one copied NPC VMAD apply script.", false,
            "M7 bounded read-only inspection: reports the copied plugin hash, target NPC, reserved FO4/SSE apply-script name, and typed property-name list; it never writes, deploys, executes Papyrus, or claims live load-order/runtime behavior."),
        Descriptor("outfit create", "Create a typed outfit proposal (alias for outfit propose).", true,
            "P09 compatibility alias; uses the hash-bound outfit proposal contract and requires the same explicit K-local inputs as outfit propose."),
        Descriptor("plugin verify", "Independently verify a written plugin.", false, "M3 slice: legacy typed-field verification plus proposal-bound hash, target FormID, changed fields, preserved subrecords, record boundaries, and binary fixture checks; unsupported structures fail closed."),
        Descriptor("plugin audit", "Compare the complete typed record surface of two copied plugins.", false,
            "M10 bounded read-only audit: compares record identities and typed summaries, reports added/removed/changed records and risky world/scene families, and never resolves live provider precedence, deploys a plugin, or claims runtime loadability."),
        Descriptor("plugin deploy", "Deploy one hash-bound plugin to a copied Data root.", true,
            "M9 bounded deployment: accepts only .esp/.esm/.esl files and an explicit SHA-256, writes only to an existing K-local copied Data root, treats an identical destination as idempotent, refuses conflicts and reparse paths, and never targets the protected live root."),
        Descriptor("runtime smoke verify", "Validate operator-supplied runtime smoke evidence.", false,
            "M9 read-only evidence gate: validates schema, provider identity, package hash, environment fingerprint, required screenshots, and control-NPC metadata for one copied FO4 or SSE report; it never judges screenshot pixels or creates runtime proof."),
        Descriptor("runtime smoke verify-all", "Validate both operator-supplied runtime smoke reports.", false,
            "M9 read-only evidence gate: runs the typed validator for both copied FO4 and SSE reports against one package acceptance report and returns one aggregate result; it never judges screenshot pixels or creates runtime proof."),
        new CommandDescriptor(
            "npc assembly preflight",
            "Join hash-bound package, actor identity, body-morph ownership, and outfit provenance evidence.",
            "1",
            false,
            ImmutableArray.Create(GameEdition.SkyrimSpecialEdition),
            ImmutableArray.Create("Read-only static preflight; no BodySlide execution, package write, runtime proof, or visual authority.")),
        Descriptor("package build", "Assemble a verified installable package.", true,
            "P12 bounded package builder; consumes explicit K-local artifacts, validates hashes and paths, and never deploys to a live game root."),
        Descriptor("package inspect", "Inspect a typed preset-to-NPC package manifest.", false,
            "P12 bounded read-only manifest inspection: validates schema, identity, artifact paths, sizes, and hashes without reading artifact bytes or changing the package."),
        Descriptor("package verify", "Verify every declared package artifact and reject undeclared files.", false,
            "P12 bounded independent package verification: re-hashes every manifest artifact below a K-local package root, checks sizes and safe paths, and never mutates or claims runtime behavior. Exact receipt-free Finish workflows are eligible for static verification; supplied review receipts remain fully validated."),
        Descriptor("package archive", "Create and reopen a verified no-wrapper install ZIP.", true,
            "P12 bounded Manager-authored archive write: reverifies a K-local package, maps only declared Data payload to install root, adds deterministic runtime instructions, refuses overwrite, and independently reopens every entry without deployment or runtime claims. Exact receipt-free Finish workflows are eligible for archive creation; supplied review receipts remain fully validated."),
        Descriptor("render npc", "Render a deterministic off-engine preview (alias for preview render).", true,
            "M6 compatibility alias; uses the typed preview-scene contract and preserves its K-only, non-runtime rendering limits."),
        Descriptor("pipeline preset-to-npc", "Compose a typed preset into a bounded NPC package.", true,
            "P12 composition: typed identity/name/weight and canonical preset mapping, plugin/BodyGen/BodySlide package artifacts, optional FaceGeom/FaceTint and runtime-script evidence or packaged apply-PEX inputs, hash-bound manifest, and runtime-test kit; game-facing binary serialization and runtime proof remain separate."),
        SkyrimDescriptor("npc voice discover", "Discover compatible local XTTS services and report storage safety.", false,
            "Read-only loopback discovery; relative or unverified service storage blocks synthesis, and request text is logged by the external service."),
        SkyrimDescriptor("npc voice import", "Validate and normalize a hash-bound NPC reference-voice WAV.", true,
            "Writes a fresh K-local sample authority and normalized WAV; it never modifies or uploads the original sample."),
        SkyrimDescriptor("npc voice synthesize", "Synthesize a reviewed dialogue manifest through one local XTTS service.", true,
            "Writes resumable K-local WAVs and a synthesis ledger; no runtime, listening, or voice-likeness authority is established."),
        SkyrimDescriptor("npc dialogue analyze", "Create or analyze a reviewed custom-dialogue manifest.", true,
            "Template mode writes a draft; analysis plans hash-bound records and assets without changing a plugin, and refuses a source that already owns INFO records because existing dialogue/audio import is unsupported."),
        SkyrimDescriptor("npc dialogue apply", "Apply a reviewed dialogue proposal and synthesized voice assets.", true,
            "Writes a fresh K-local dialogue overlay onto the original NPC package: rewritten plugin, new voice assets, PEX, and preserved-plus-appended DataRoot SEQ only; existing FaceGen/skin assets remain in the source package, lip tools are external, and static output does not establish game-runtime behavior."),
        SkyrimDescriptor("npc dialogue verify", "Independently verify a custom-dialogue output manifest.", false,
            "Read-only static verification; it does not establish listening quality, visual acceptance, or game-runtime behavior."),
        Descriptor("gui", "Launch the accessible desktop shell.", false)
    ];

    private static readonly ImmutableDictionary<string, ImmutableArray<string>> LedgerMap =
        new Dictionary<string, ImmutableArray<string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["gui"] = ["P12-001"],
            ["facegen bake-all"] = ["P12-002"],
            ["facegen build-geom"] = ["P12-003"],
            ["facegen diagnose"] = ["P12-004"],
            ["capabilities"] = ["P12-005"],
            ["schema export"] = ["P12-006"],
            ["package build"] = ["P12-007"],
            ["package inspect"] = ["P12-007"],
            ["package verify"] = ["P12-007"],
            ["package archive"] = ["P12-007"],
            ["pipeline preset-to-npc"] = ["P12-007"],
            ["npc create-from-preset"] = ["P12-007"],
            ["npc create-from-jslot"] = ["P12-007"]
        }.ToImmutableDictionary(StringComparer.OrdinalIgnoreCase);

    public static ImmutableArray<string> LedgerIdsFor(string commandName) =>
        LedgerMap.TryGetValue(commandName, out var ids) ? ids : [];

    private static CommandDescriptor Descriptor(string name, string description, bool mutates, string? limitation = null) =>
        new(name, description, "1", mutates,
            ImmutableArray.Create(GameEdition.Fallout4, GameEdition.SkyrimSpecialEdition),
            ImmutableArray.Create(limitation ?? "M1 shell: feature implementation is introduced by later milestones."));

    private static CommandDescriptor SkyrimDescriptor(
        string name,
        string description,
        bool mutates,
        string limitation) =>
        new(
            name,
            description,
            "1",
            mutates,
            ImmutableArray.Create(
                GameEdition.SkyrimSpecialEdition),
            ImmutableArray.Create(limitation));
}
