<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BSA_BA2_Library_DLL">
      <HintPath>..\..\..\..\..\..\tools\external\fo4-npc-manager-1.3.4\BSA_BA2_Library_DLL.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
