<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><AssemblyName>NpcManager.Formats.Bethesda</AssemblyName><RootNamespace>NpcManager.Formats.Bethesda</RootNamespace><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NpcManager.Application\NpcManager.Application.csproj" />
    <ProjectReference Include="..\NpcManager.Domain\NpcManager.Domain.csproj" />
    <PackageReference Include="Mutagen.Bethesda.Fallout4" Version="0.52.0" />
    <PackageReference Include="Mutagen.Bethesda.Skyrim" Version="0.52.0" />
  </ItemGroup>
</Project>
