using NpcManager.Application;
using NpcManager.Domain;
using NpcManager.Infrastructure;

namespace NpcManager.Cli;

/// <summary>
/// Typed composition boundary for the CLI runner.
///
/// Keeping the application services in one immutable bundle prevents the
/// command router from becoming a service-locator or a constructor-sized
/// dependency graph. Optional handlers remain explicit: a route is unavailable
/// when its service is not supplied, and the runner reports that state rather
/// than falling back to late-bound dispatch.
/// </summary>
public sealed record CliRunnerServices(
    IWorkspacePreflightService preflightService,
    IGameInventoryService inventoryService,
    IFormChoiceService formChoiceService,
    IAssetChoiceService assetChoiceService,
    IGameRootPreflightService gameRootPreflightService,
    IArchiveConsistencyService archiveConsistencyService,
    GeneratedArtifactCommandHandler generatedArtifactCommands,
    BodySidecarCommandHandler bodySidecarCommands,
    IAssetIndexExportService assetIndexExportService,
    INpcMutationService mutationService,
    INpcTemplateMaterializationService templateMaterializationService,
    INpcResetService resetService,
    IPresetService presetService,
    IPresetFormResolver formResolver,
    IFaceGenService faceGenService,
    IBodyGenService bodyGenService,
    IPresetToNpcPipeline pipeline,
    IPluginLoadOrderService pluginLoadOrderService,
    WorkspacePath workspaceRoot,
    INpcFacePatchService? facePatchService = null,
    IFaceGenOptionsService? faceGenOptionsService = null,
    INpcFaceTintPatchService? faceTintPatchService = null,
    ISkyrimFaceMorphPatchService? skyrimFaceMorphPatchService = null,
    IRaceMenuExtendedMorphPatchService? raceMenuExtendedMorphPatchService = null,
    ISkyrimFaceTintPatchService? skyrimFaceTintPatchService = null,
    IRaceMenuSculptPatchService? raceMenuSculptPatchService = null,
    IFacePoseResolver? facePoseResolver = null,
    IFaceResetService? faceResetService = null,
    IBodySlideResolutionService? bodySlideResolutionService = null,
    ISseBodyWeightResolutionService? sseBodyWeightResolutionService = null,
    IBodyOverlayPatchService? bodyOverlayPatchService = null,
    ISkyrimOverlayFoldService? skyrimOverlayFoldService = null,
    ISkyrimBodyTransformService? skyrimBodyTransformService = null,
    IBodyResetService? bodyResetService = null,
    IFaceGeomBuildService? faceGeomBuildService = null,
    IFaceTintBuildService? faceTintBuildService = null,
    IFaceGenCorrectionService? faceGenCorrectionService = null,
    IFaceGenBatchService? faceGenBatchService = null,
    IFaceGenPluginBuildService? faceGenPluginBuildService = null,
    IPreviewSceneService? previewSceneService = null,
    IPreviewRerollService? previewRerollService = null,
    IPreviewNifExportService? previewNifExportService = null,
    IOutfitChoiceService? outfitChoiceService = null,
    IOutfitProposalService? outfitProposalService = null,
    ILeveledListProposalService? leveledListProposalService = null,
    ILeveledListResolveService? leveledListResolveService = null,
    IArmorProposalService? armorProposalService = null,
    IArmorDamageResistanceService? armorDamageResistanceService = null,
    IArmorAddonProposalService? armorAddonProposalService = null,
    IArmorAddonModelProposalService? armorAddonModelProposalService = null,
    IMaterialSwapProposalService? materialSwapProposalService = null,
    IObjectTemplateProposalService? objectTemplateProposalService = null,
    IObjectTemplatePropertyProposalService? objectTemplatePropertyProposalService = null,
    IChangeTrackingService? changeTrackingService = null,
    IChangeActionService? changeActionService = null,
    IRecordProposalService? recordProposalService = null,
    IPluginWriteService? pluginWriteService = null,
    IPluginVerifyService? pluginVerifyService = null,
    IBodySidecarWriteService? bodySidecarWriteService = null,
    IRuntimeScriptProposalService? runtimeScriptProposalService = null,
    IRuntimeScriptBuildService? runtimeScriptBuildService = null,
    ISchemaExportService? schemaExportService = null,
    IDesktopLaunchService? desktopLaunchService = null,
    IOutfitBinaryWriteService? outfitBinaryWriteService = null,
    ILeveledListBinaryWriteService? leveledListBinaryWriteService = null,
    IArmorBinaryWriteService? armorBinaryWriteService = null,
    IArmorAddonBinaryWriteService? armorAddonBinaryWriteService = null,
    IMaterialSwapBinaryWriteService? materialSwapBinaryWriteService = null,
    IObjectTemplateBinaryWriteService? objectTemplateBinaryWriteService = null,
    IRuntimeScriptBinaryWriteService? runtimeScriptBinaryWriteService = null,
    IRuntimeScriptPackageService? runtimeScriptPackageService = null,
    IRuntimeScriptDeployService? runtimeScriptDeployService = null,
    IFaceGeomBinaryBuildService? faceGeomBinaryBuildService = null,
    IPreviewNifBinaryExportService? previewNifBinaryExportService = null,
    IFaceGenProviderResolutionService? faceGenProviderResolutionService = null,
    IFaceGenPackPlanService? faceGenPackPlanService = null,
    IFaceTintProviderBoundBuildService? faceTintProviderBoundBuildService = null,
    IFaceGeomProviderBoundBuildService? faceGeomProviderBoundBuildService = null,
    IRuntimeScriptVmadInspectService? runtimeScriptVmadInspectService = null,
    IFaceGenPackService? faceGenPackService = null,
    IPackageBuildService? packageBuildService = null,
    IPackageInspectService? packageInspectService = null,
    IPackageVerifyService? packageVerifyService = null,
    IPackageArchiveService? packageArchiveService = null,
    IPluginSurfaceAuditService? pluginSurfaceAuditService = null,
    IRuntimeSmokeVerifyService? runtimeSmokeVerifyService = null,
    IPluginDeployService? pluginDeployService = null,
    IFaceGenDeployService? faceGenDeployService = null,
    IPreviewAnimationListService? previewAnimationListService = null,
    IPreviewAnimationTreeService? previewAnimationTreeService = null,
    IProfileScanService? profileScanService = null,
    IRecordListingService? recordListingService = null,
    IBlankNpcBuildService? blankNpcBuildService = null,
    IRaceMenuNpcBuildService? raceMenuNpcBuildService = null,
    IExistingNpcEditService? existingNpcEditService = null,
    ISkyrimNativeFaceTintPipelineService? skyrimNativeFaceTintPipelineService = null,
    IFaceGenBakeAllService? nativeFaceGenBatchService = null,
    IReviewedGameIntakeService? reviewedGameIntakeService = null,
    IRaceMenuPresetCatalogService? raceMenuPresetCatalogService = null,
    ISkyrimFaceRecordPluginAuthorityLoader? skyrimFaceRecordPluginAuthorityLoader = null,
    ISkyrimHeadPartChoiceService? skyrimHeadPartChoiceService = null,
    ISkyrimRaceMenuPaintChoiceService? skyrimRaceMenuPaintChoiceService = null,
    IRaceMenuJslotNpcBuildService? raceMenuJslotNpcBuildService = null,
    IBodySlideSliderPresetInspectionService? bodySlideSliderPresetInspectionService = null,
    IReferencePresetAuthoringTransaction? referencePresetAuthoringTransaction = null,
    IReferencePresetSessionService? referencePresetSessionService = null,
    IRaceMenuNpcExecutionRequestFileLoader? referencePresetExecutionRequestFileLoader = null,
    ISkyrimFollowerFinishService? skyrimFollowerFinishService = null,
    ISkyrimFollowerFinishRequestFileLoader? skyrimFollowerFinishRequestFileLoader = null,
    ISkyrimFollowerFinishPairService? skyrimFollowerFinishPairService = null,
    IPreviewServiceFactory<INpcVisualPreviewComposer>?
        npcVisualPreviewFactory = null,
    IPreviewServiceFactory<FaceGeomHairRegionsPreviewServices>?
        faceGeomHairRegionsPreviewFactory = null,
    IActorAssemblyPreflightService? actorAssemblyPreflightService = null,
    ISkyrimNpcFinishCoreService? skyrimNpcFinishCoreService = null,
    ISkyrimInteriorPlacementService? skyrimInteriorPlacementService = null,
    INpcBuildPreflightService? npcBuildPreflightService = null,
    Func<WorkspacePath, ILocalOperationJournal>? localOperationJournalFactory = null,
    ISkyrimNpcVoiceService? skyrimNpcVoiceService = null,
    ISkyrimNpcDialogueService? skyrimNpcDialogueService = null);
